### ISSUE TITLE
풀이 방법 토론해요 (PGS Lv2. 모음사전)

### ISSUE THREAD

**Issue by julia8024** [Coding-Crew-Forever/Coding-Test-Study#54]
다들 이 문제 어떤 방법으로 푸실건가요?
재밌게 풀어주세요 :)

[프로그래머스 Lv2. 모음사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)

**Comment by ahma0** [comment]
흑흑 함 도전해봣는데 넘 어렵네요 어케 풀엇나요?

저는 규칙 찾아서 풀었어요

| 문자열 | 순서 |
| :---: | :---: |
| A | 1 |
| AA | 2 |
| AAA | 3 |
| AAAA | 4 |
| AAAAA | 5 |
| AAAAE | 6 |
| AAAAI | 7 |
| ... | ... |
| AAAE | 10 |
| ... | ... |
| AAAI | 16 |

이걸로 문자열 끝자리에 따라 차이나는게 다른 것 같아서

_ _ _ _ ? 처럼 다섯 번째 자리면 1씩
_ _ _ ?   처럼 네 번째 자리면 6씩 차이나길래 

각 자리 수의 가중치가

5<sup>4</sup> 5<sup>3</sup> 5<sup>2</sup> 5<sup>1</sup> 5<sup>0</sup>

씩 차이나니까 누적해서 더하면 문자 바뀔 때마다 781, 156, 31, 6, 1씩 차이남요.. 

A E I O U 각각에 1 2 3 4 5라는 숫자를 부여해서 각 자리 숫자가 바뀔 때마다 저 숫자를 곱해서 더해줫어요.

#57

**Comment by julia8024** [comment]
저도 비슷하게 풀었어요
저는 A E I O U 각각에 0 ~ 4까지 숫자를 부여하고, 계산할 때 +1 한 게 다르긴 하네요 (별 차이 없음)
