### ISSUE TITLE
재귀함수에서 증감연산자 쓰면 안되는 이유?

### ISSUE THREAD

**Issue by hhJ830** [Coding-Crew-Forever/Coding-Test-Study#55]
method(n + arr[index], index+1); 여기서 index+1을 ++index로 쓰면 안되는 이유가 뭘까요?
현재 index=1이면 ++index=2이고 index+1=2인 상태에서 재귀 호출하니까
method 함수의 매개변수로 있는 index를 2로 받아와서 둘 다 결과가 같아야 하는게 아닌가...
증감연산자 쓰면 ArrayIndexOutOfBoundsException 오류가 나요

`

static void method(int n, int index){
        if(index == N){
            min = Math.min(min, n);
            max = Math.max(max, n);
            return;
        }

        for(int i=0;i<4;i++){
            if(op[i] > 0) {
                op[i]--;

                switch (i) {
                    case 0:
                        method(n + arr[index], index+1);
                        break;
                    case 1:
                        method(n - arr[index], index+1);
                        break;
                    case 2:
                        method(n * arr[index], index+1);
                        break;
                    case 3:
                        method(n / arr[index], index+1);
                        break;
                }
                op[i]++;
            }
        }
    }

`

**Comment by chaeryeon823** [comment]
++index를 쓰면 index의 값 자체가 +1 이되어 변형 되기 때문인거 같아요. 전체 코드를 올려주시면 확실히 알 수 있을 것 같네요.😀

**Comment by hhJ830** [comment]
헉 바보였네요 감사합니다 :)
